version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=Feature4
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'

  app:
    build: .
    image: miapp-springboot
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/Feature4
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:1234@postgres:5432/Feature4?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres

volumes:
  grafana-data:
